// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4fFWM7PWYPuefS04bC79-e3TIWxnguP4',
    appId: '1:829425322627:web:8480f4c2be54c1de51e9b6',
    messagingSenderId: '829425322627',
    projectId: 'e-mart-f4c0b',
    authDomain: 'e-mart-f4c0b.firebaseapp.com',
    storageBucket: 'e-mart-f4c0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8IhiGhpbJ2icIagtS38vt1JshE5JeSY',
    appId: '1:829425322627:android:219adbd75ebc147f51e9b6',
    messagingSenderId: '829425322627',
    projectId: 'e-mart-f4c0b',
    storageBucket: 'e-mart-f4c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYrBQAqojzSDe2e7gv_5r712KIwGgmIRA',
    appId: '1:829425322627:ios:52ce1af91cec73f851e9b6',
    messagingSenderId: '829425322627',
    projectId: 'e-mart-f4c0b',
    storageBucket: 'e-mart-f4c0b.appspot.com',
    androidClientId: '829425322627-vk4nnu6265e7cf70ae1eq6ofaqc0ka19.apps.googleusercontent.com',
    iosClientId: '829425322627-53jg4t1okpsgv6d09mid9iosntmgaihr.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYrBQAqojzSDe2e7gv_5r712KIwGgmIRA',
    appId: '1:829425322627:ios:52ce1af91cec73f851e9b6',
    messagingSenderId: '829425322627',
    projectId: 'e-mart-f4c0b',
    storageBucket: 'e-mart-f4c0b.appspot.com',
    androidClientId: '829425322627-vk4nnu6265e7cf70ae1eq6ofaqc0ka19.apps.googleusercontent.com',
    iosClientId: '829425322627-53jg4t1okpsgv6d09mid9iosntmgaihr.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );
}
